# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_firebase: &firebase
  firebase:
    api_key: <%= ENV['FIREBASE_API_KEY'] %>
    auth_domain: <%= ENV['FIREBASE_AUTH_DOMAIN'] %>
    database_url: <%= ENV['FIREBASE_DATABASE_URL'] %>
    storage_bucket: <%= ENV['FIREBASE_STORAGE_BUCKET'] %>
    messaging_sender_id: <%= ENV['FIREBASE_MESSAGING_SENDER_ID'] %>

development:
  <<: *firebase
  secret_key_base: ac898037e7f3c3d446ca27651664c77967c70546344e0fc943075d57d95e0193233b83c9e33f7620a38904b02a11d5721d887debd0cfeafdd014e7de2e4f6bd1

test:
  <<: *firebase
  secret_key_base: 97e1c139eda96c0f3e2e0752352aab9ef712fc6864fa7ad3e5fbc4d25c917f91b55a959428d3a05960d0838135a0f6ccd46423b77029081e841d1d0febff2a2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *firebase
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
